input_data_path: "data/raw/heart.csv"
output_data_path: "models/predictions.csv"
model_path: "models/model.pkl"
metric_path: "models/metrics.json"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop: ["target"]
  target_col: "target"